

export const data = [
  {
    "title": "A Doctor in the House",
    "author": "Candy Carson",
    "rating": 5.00,
    "reviews_count": 1,
    "price_range": "$6.50 – $16.99",
    "description": "Dicta sunt explicabo. Nemo enim ipsam voluptatem voluptas sit odit aut fugit, sed quia consequuntur. Lorem ipsum dolor. Aquia sit amet, elitr, sed diam nonum eirmod tempor invidunt.",
    "publisher": "Brandon & Partners",
    "year": 2015,
    "pages": 350,
    "isbn": "2544555561",
    "format": ["Online Book", "Paper Book"],
    "image": "https://i.ibb.co.com/RfBZDVg/81j-RGe9r-y-L-UF894-1000-QL80.jpg"
  },
  {
    "title": "Shadows of Glass",
    "author": "Elena Hart",
    "rating": 4.87,
    "reviews_count": 142,
    "price_range": "$7.99 – $18.50",
    "description": "A haunting tale of fractured realities, betrayal, and redemption set in a city where memories are currency.",
    "publisher": "Silverleaf Press",
    "year": 2021,
    "pages": 420,
    "isbn": "9781423399123",
    "format": ["Online Book", "Paper Book"],
    "image": "https://i.ibb.co.com/wZptCNM1/9781785305542.jpg"
  },
  {
    "title": "Crimson Tide",
    "author": "Marcus Vane",
    "rating": 4.95,
    "reviews_count": 97,
    "price_range": "$9.50 – $20.00",
    "description": "An elite assassin is drawn back into the game after a mysterious organization puts a bounty on his head.",
    "publisher": "Blackmoon Books",
    "year": 2019,
    "pages": 385,
    "isbn": "9781936594719",
    "format": ["Online Book", "Paper Book"],
    "image": "https://i.ibb.co.com/2YyqYPhq/9186yeema-UL-UF1000-1000-QL80.jpg"
  },
  {
    "title": "City of Ashes",
    "author": "Nora Bellamy",
    "rating": 4.73,
    "reviews_count": 211,
    "price_range": "$8.20 – $17.99",
    "description": "When a great fire reduces the capital to ruins, an orphaned thief must rise to become the city’s last hope.",
    "publisher": "Iron Quill Publishing",
    "year": 2018,
    "pages": 410,
    "isbn": "9781442497831",
    "format": ["Online Book", "Paper Book"],
    "image": "https://i.ibb.co.com/YTB5L4Ks/81h-p-Tvx-Rm-L.jpg"
  },
  {
    "title": "The Silent Storm",
    "author": "Daniel Cross",
    "rating": 4.89,
    "reviews_count": 154,
    "price_range": "$6.75 – $15.80",
    "description": "In a remote fishing town, a detective uncovers a conspiracy that could destroy the nation.",
    "publisher": "Stormlight Press",
    "year": 2020,
    "pages": 360,
    "isbn": "9780747532699",
    "format": ["Online Book", "Paper Book"],
    "image": "https://i.ibb.co.com/TMWKn6X4/612-T1-HKVy-OL.jpg"
  },
  {
    "title": "Midnight Masquerade",
    "author": "Sophia Arden",
    "rating": 4.91,
    "reviews_count": 132,
    "price_range": "$7.10 – $19.99",
    "description": "A gripping romance thriller set in the underbelly of Venice's most dangerous masquerade ball.",
    "publisher": "Golden Ink",
    "year": 2022,
    "pages": 330,
    "isbn": "9781408855652",
    "format": ["Online Book", "Paper Book"],
    "image": "https://i.ibb.co.com/MyKTnDhY/71prl-E0-Cfr-L.jpg"
  },
  {
    "title": "Neon Empire",
    "author": "Alex Kane",
    "rating": 4.78,
    "reviews_count": 119,
    "price_range": "$8.99 – $21.50",
    "description": "In a cyberpunk metropolis, a rogue hacker battles mega-corporations for freedom and survival.",
    "publisher": "Neon Press",
    "year": 2021,
    "pages": 395,
    "isbn": "9780553579901",
    "format": ["Online Book", "Paper Book"],
    "image": "https://i.ibb.co.com/MyN37cwQ/714-g-Gh9p-AL-UF1000-1000-QL80.jpg"
  },
  {
    "title": "The Last Alchemist",
    "author": "Julian Cole",
    "rating": 4.92,
    "reviews_count": 186,
    "price_range": "$7.25 – $18.75",
    "description": "A fantasy epic where the last surviving alchemist must prevent an ancient prophecy from coming true.",
    "publisher": "Arcane House",
    "year": 2017,
    "pages": 500,
    "isbn": "9780671027360",
    "format": ["Online Book", "Paper Book"],
    "image": "https://i.ibb.co.com/w5f7fGb/36247279.jpg"
  },
  {
    "title": "Echoes of the Forgotten",
    "author": "Clara Night",
    "rating": 4.84,
    "reviews_count": 178,
    "price_range": "$6.99 – $16.50",
    "description": "A gripping mystery spanning generations, where secrets buried in an old mansion resurface.",
    "publisher": "Evernight Publishing",
    "year": 2016,
    "pages": 370,
    "isbn": "9780743273565",
    "format": ["Online Book", "Paper Book"],
    "image": "https://i.ibb.co.com/tTHMqFVv/71p0-Q6-IUG-L-UF1000-1000-QL80.jpg"
  },
  {
    "title": "Blood Moon Rising",
    "author": "Liam Draven",
    "rating": 4.97,
    "reviews_count": 205,
    "price_range": "$9.99 – $22.00",
    "description": "A supernatural thriller where werewolves battle for control under the crimson light of a blood moon.",
    "publisher": "Darkfang Press",
    "year": 2023,
    "pages": 410,
    "isbn": "9780385504201",
    "format": ["Online Book", "Paper Book"],
    "image": "https://i.ibb.co.com/0pPdFTHJ/71b-JJXVxl-VL-UF1000-1000-QL80.jpg"
  },
   {
    "title": "The Silent Storm",
    "author": "Daniel Cross",
    "rating": 4.89,
    "reviews_count": 154,
    "price_range": "$6.75 – $15.80",
    "description": "In a remote fishing town, a detective uncovers a conspiracy that could destroy the nation.",
    "publisher": "Stormlight Press",
    "year": 2020,
    "pages": 360,
    "isbn": "9780747532699",
    "format": ["Online Book", "Paper Book"],
    "image": "https://i.ibb.co.com/TMWKn6X4/612-T1-HKVy-OL.jpg"
  },
  {
    "title": "Midnight Masquerade",
    "author": "Sophia Arden",
    "rating": 4.91,
    "reviews_count": 132,
    "price_range": "$7.10 – $19.99",
    "description": "A gripping romance thriller set in the underbelly of Venice's most dangerous masquerade ball.",
    "publisher": "Golden Ink",
    "year": 2022,
    "pages": 330,
    "isbn": "9781408855652",
    "format": ["Online Book", "Paper Book"],
    "image": "https://i.ibb.co.com/MyKTnDhY/71prl-E0-Cfr-L.jpg"
  },
  
]
